### ISSUE TITLE
Ubuntu version?

### ISSUE THREAD

**Issue by PranjalBiswas** [Yang7879/3D-RecGAN-extended#6]
Which version of Ubuntu (14.04, 16.04 etc) have you tested your code on? I think you can specify that in your requirement section.

**Comment by Yang7879** [comment]
@PranjaLBiswas27 Both OS versions are ok with the environment of python 2.7 and tensorflow 1.2 .

**Comment by PranjalBiswas** [comment]
Thank you for the info.
